# Generated by Django 4.2.6 on 2023-10-13 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_auto_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'Suv'), ('universal', 'Universal'), ('coupe', 'Coupe')], max_length=9),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,20}$', 'First letter uppercase min 2 max 20 ch')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
