# Generated by Django 4.2.6 on 2023-10-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_body_alter_carmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['id']},
        ),
    ]
