# Generated by Django 4.2.6 on 2023-10-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('auto_parks', '0002_autoparkmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_parks', to='users.usermodel'),
        ),
    ]
