# Generated by Django 4.2.6 on 2023-10-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('auto_parks', '0002_autoparkmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_parks', to='Users.usersmodel'),
        ),
    ]
